name: 'Dependency Review'
on: [pull_request]

jobs:
  dependency-review:
    runs-on: ubuntu-latest
    steps:
      - name: 'Checkout Repository'
        uses: actions/checkout@v3
      - name: 'Dependency Review'
        id: dr_test
        uses: actions/dependency-review-action@laughedelic:feat/data-outputs
      - name: 'print new outputs test'
        run: echo ${{join(steps.dr_test.outputs.*, '\n')}}
